export const OBRAS = [
  {
    id: 'le',
    abbr: 'LE',
    shortLabel: 'Livro dos Espíritos',
    label: 'O Livro dos Espíritos',
    year: 'Paris, 1857 — Primeira obra da codificação',
    summary: 'Os fundamentos da doutrina: Deus, Espíritos, alma, reencarnação e leis morais. Base de todo o estudo espírita.',
    topics: [
      {
        title: 'Parte I — Das Causas Primárias',
        subtitle: 'Deus, os Espíritos e a criação',
        context: 'Kardec abre a obra com as perguntas mais fundamentais da existência humana. O que é Deus, quem são os Espíritos e qual é a origem e o propósito da criação.',
        items: ['O que é Deus? (Q.1)', 'Atributos da Divindade (Q.13)', 'Providência divina (Q.963)', 'O que são os Espíritos? (Q.76)', 'Origem dos Espíritos (Q.78)', 'Mundos habitados (Q.55)'],
      },
      {
        title: 'Parte II — Do Mundo Espiritual',
        subtitle: 'Alma, encarnação, reencarnação e vida após a morte',
        context: 'A parte mais extensa da obra. Trata da natureza da alma, do perispírito, do processo de encarnação e reencarnação, da vida entre as encarnações e do que acontece após a morte física.',
        items: ['O que é a alma? (Q.134)', 'O perispírito (Q.93)', 'Por que nos encarnamos? (Q.132)', 'Reencarnação (Q.166)', 'Vida após a morte (Q.149)', 'Espíritos felizes e sofredores (Q.165)'],
      },
      {
        title: 'Parte III — Das Leis Morais',
        subtitle: 'As leis divinas que regem a existência',
        context: 'Kardec apresenta as grandes leis naturais como expressão da vontade divina: adoração, trabalho, reprodução, conservação, destruição, sociedade, progresso, igualdade, liberdade, justiça e amor.',
        items: ['A lei do amor e da caridade (Q.614)', 'A lei do trabalho (Q.664)', 'Livre-arbítrio (Q.843)', 'A lei da igualdade (Q.803)', 'Virtudes e vícios (Q.893)'],
      },
      {
        title: 'Parte IV — Das Esperanças e Consolações',
        subtitle: 'O destino do Espírito e a vida futura',
        context: 'A parte conclusiva responde às grandes angústias humanas: existem penas eternas? O que é o paraíso? Kardec apresenta uma visão de justiça divina baseada no progresso infinito.',
        items: ['Penas eternas — sim ou não? (Q.1009)', 'O progresso dos Espíritos (Q.780)', 'Mundos superiores (Q.188)', 'A felicidade futura (Q.920)'],
      },
    ],
  },
  {
    id: 'lm',
    abbr: 'LM',
    shortLabel: 'Livro dos Médiuns',
    label: 'O Livro dos Médiuns',
    year: 'Paris, 1861 — Segunda obra da codificação',
    summary: 'Mediunidade, evocações, tipos de manifestações e como discernir os Espíritos.',
    topics: [
      {
        title: 'Parte I — Dos Agentes Mediúnicos',
        subtitle: 'Quem são os médiuns e os Espíritos',
        context: 'Kardec explica quem são os agentes das comunicações espíritas: de um lado os Espíritos, de outro os médiuns — suas faculdades, tipos e desenvolvimento.',
        items: ['O que é mediunidade?', 'Tipos de médiuns', 'Desenvolvimento mediúnico', 'Espíritos bons e maus', 'Como se comunicam os Espíritos?'],
      },
      {
        title: 'Parte II — Das Manifestações Espíritas',
        subtitle: 'Os fenômenos e como estudá-los',
        context: 'Um guia rigoroso para compreender as manifestações físicas e intelectuais dos Espíritos.',
        items: ['Manifestações físicas', 'Manifestações intelectuais', 'Mesas girantes', 'A escrita mediúnica (psicografia)', 'Como verificar a autenticidade'],
      },
      {
        title: 'Parte III — Das Evocações',
        subtitle: 'Como, quando e por que evocar',
        context: 'Kardec explica as condições para evocar Espíritos com seriedade, os riscos da leviandade e como agir com Espíritos sofredores.',
        items: ['Condições para as evocações', 'Evocação de familiares', 'Espíritos sofredores', 'Riscos das evocações frívolas', 'Como lidar com obsessões'],
      },
    ],
  },
  {
    id: 'ese',
    abbr: 'ESE',
    shortLabel: 'Evangelho',
    label: 'O Evangelho Segundo o Espiritismo',
    year: 'Paris, 1864 — Terceira obra da codificação',
    summary: 'Comentários aos ensinamentos morais do Cristo à luz da doutrina espírita. A obra da prática: caridade, humildade, perdão e amor.',
    topics: [
      {
        title: 'Parte I — Os Fundamentos Morais',
        subtitle: 'Fé, razão e os ensinamentos de Jesus',
        context: 'Kardec interpreta os ensinamentos morais do Cristo à luz da doutrina espírita.',
        items: ['Fé e razão (cap. II)', 'Bem-aventuranças (cap. V)', 'O Cristo e a doutrina', 'Sede perfeitos (cap. IV)'],
      },
      {
        title: 'Parte II — A Vida Moral na Prática',
        subtitle: 'Virtudes, vícios e o caminho do bem',
        context: 'A parte mais cotidiana da obra: caridade, humildade, perdão, tolerância.',
        items: ['Amar os inimigos (cap. XI)', 'A caridade (cap. XIII)', 'A humildade (cap. XIV)', 'O perdão das ofensas (cap. XII)'],
      },
      {
        title: 'Parte III — Provas e Consolações',
        subtitle: 'Sofrimento, prece e esperança',
        context: 'Por que sofremos? Qual o valor das tribulações? Kardec responde com profundidade e conforto espiritual.',
        items: ['Tribulações (cap. XVI)', 'A prece e sua eficácia (cap. XXVII)', 'A morte e a vida (cap. XXX)', 'O livre-arbítrio'],
      },
    ],
  },
  {
    id: 'ci',
    abbr: 'CI',
    shortLabel: 'Céu e o Inferno',
    label: 'O Céu e o Inferno',
    year: 'Paris, 1865 — Quarta obra da codificação',
    summary: 'A doutrina das penas e recompensas futuras. Exemplos de vidas e mortes narrados pelos próprios Espíritos.',
    topics: [
      {
        title: 'Parte I — Doutrina',
        subtitle: 'O que são o Céu e o Inferno para o Espiritismo',
        context: 'Kardec confronta as doutrinas tradicionais do céu, inferno e purgatório com os princípios espíritas.',
        items: ['O que é o inferno espírita?', 'Existe o purgatório?', 'O paraíso na doutrina', 'Penas eternas — sim ou não?'],
      },
      {
        title: 'Parte II — Exemplos',
        subtitle: 'Narrativas reais de vidas e mortes',
        context: 'Relatos de Espíritos em diferentes condições após a morte — sofrendo, felizes, arrependidos, em progresso.',
        items: ['Espíritos em sofrimento', 'Espíritos felizes', 'Morte repentina e seus efeitos', 'Suicídio e consequências'],
      },
    ],
  },
  {
    id: 'gen',
    abbr: 'GEN',
    shortLabel: 'A Gênese',
    label: 'A Gênese',
    year: 'Paris, 1868 — Quinta obra da codificação',
    summary: 'Concilia ciência, filosofia e religião: a criação do universo, os milagres e a origem da vida segundo o Espiritismo.',
    topics: [
      {
        title: 'Parte I — Gênese Cosmogônica',
        subtitle: 'A criação do universo segundo o Espiritismo',
        context: 'Kardec aborda a criação do universo a partir de uma perspectiva que concilia ciência e espiritualidade.',
        items: ['A criação segundo o Espiritismo', 'A formação dos mundos', 'Anjos e demônios', 'Milagres e leis naturais'],
      },
      {
        title: 'Parte II — Gênese Biológica e Moral',
        subtitle: 'A origem do homem e da moral',
        context: 'A segunda parte trata da origem do homem físico e moral.',
        items: ['A origem do homem', 'Adão e Eva — interpretação espírita', 'Os milagres de Jesus explicados', 'Ressurreição e reencarnação'],
      },
    ],
  },
];
