"""Records the assembled system prompts as they are today.

Run BEFORE the profile seam refactor. The fixtures it writes are the only proof
that threading a profile through prompt assembly changed nothing: comparing the
refactor against fixtures generated by the refactor itself would prove only that
it agrees with itself.

    uv run python -m scripts.capture_prompt_baseline

Re-running after the refactor should leave the files untouched. If it does not,
the seam is not inert and the diff says exactly where.

See docs/superpowers/specs/2026-07-28-profile-seam-design.md
"""

import pathlib

from src.rag.explicador_prompt import build_explicador_messages
from src.rag.prompt import build_messages

FIXTURES = (
    pathlib.Path(__file__).parent.parent / "tests" / "fixtures" / "prompt_baseline"
)

_CHUNKS = [
    {
        "content": "A encarnação tem por fim fazê-los progredir.",
        "metadata": {
            "book": "O Livro dos Espíritos",
            "chapter_title": "Da Encarnação",
            "item_number": "132",
        },
    },
    {
        "content": "Amai-vos uns aos outros e fazei aos outros o que quereríeis.",
        "metadata": {
            "book": "O Evangelho Segundo o Espiritismo",
            "chapter_title": "Amai o Vosso Próximo",
            "item_number": "4",
        },
    },
]

# Carries the canonical chapter reference as well as the title — the case the
# source chips use, and the one where the header used to disagree with them.
_CHUNKS_WITH_CHAPTER_REF = [
    {
        "content": "O perispírito é o traço de união entre a vida corpórea e a espiritual.",
        "metadata": {
            "book": "A Gênese",
            "chapter": "CAPÍTULO XIV",
            "chapter_title": "OS FLUIDOS",
            "item_number": "22",
        },
    }
]

_HISTORY = [
    {"role": "user", "content": "o que é o perispírito?"},
    {"role": "assistant", "content": "É o envoltório semimaterial do espírito."},
]

_RELATED = [
    {
        "content": "O egoísmo é a chaga da sociedade.",
        "metadata": {
            "book": "O Evangelho Segundo o Espiritismo",
            "chapter_title": "Fora da Caridade",
            "item_number": "11",
        },
    }
]

# Every combination the current code can produce. A case missing here is a case
# the refactor is free to break unnoticed.
CHAT_CASES = {
    "chat_plain": dict(add_caveat=False, sensitive=False),
    "chat_caveat": dict(add_caveat=True, sensitive=False),
    "chat_sensitive": dict(add_caveat=False, sensitive=True),
    "chat_caveat_sensitive": dict(add_caveat=True, sensitive=True),
}

STUDY_CASES = {
    "study_plain": dict(footnote_context="", chapter_commentary_chunks=None),
    "study_footnotes": dict(
        footnote_context="[Nota 1] Explicação editorial.",
        chapter_commentary_chunks=None,
    ),
    "study_commentary": dict(footnote_context="", chapter_commentary_chunks=_RELATED),
    "study_full": dict(
        footnote_context="[Nota 1] Explicação editorial.",
        chapter_commentary_chunks=_RELATED,
    ),
}


def capture() -> dict[str, str]:
    out = {}
    for name, kwargs in CHAT_CASES.items():
        system, messages = build_messages(
            "o que Kardec diz sobre julgar os outros?",
            _CHUNKS,
            _HISTORY,
            10,
            **kwargs,
        )
        out[name] = system
        out[name + ".messages"] = repr(messages)

    system, messages = build_messages(
        "o que é o perispírito?", _CHUNKS_WITH_CHAPTER_REF, [], 10
    )
    out["chat_chapter_ref"] = system
    out["chat_chapter_ref.messages"] = repr(messages)

    for name, kwargs in STUDY_CASES.items():
        system, messages = build_explicador_messages(
            "14. Tende muito cuidado com o que ouvis.",
            _RELATED,
            markers=False,
            **kwargs,
        )
        out[name] = system
        out[name + ".messages"] = repr(messages)

    return out


def main() -> None:
    FIXTURES.mkdir(parents=True, exist_ok=True)
    for name, content in capture().items():
        (FIXTURES / f"{name}.txt").write_text(content, encoding="utf-8")
    print(f"wrote {len(capture())} fixtures to {FIXTURES}")


if __name__ == "__main__":
    main()
